# Generated by Django 5.0.7 on 2025-09-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='barrio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='caja_compensacion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='cesantias_fondo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='comuna',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='departamento_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='departamento_nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='eps',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='estatura_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='estrato',
            field=models.CharField(blank=True, choices=[('1', 'Estrato 1'), ('2', 'Estrato 2'), ('3', 'Estrato 3'), ('4', 'Estrato 4'), ('5', 'Estrato 5'), ('6', 'Estrato 6')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='estudia_actualmente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidato',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='municipio_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='municipio_nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='pension_fondo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='perfil_aspirante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='redes_sociales',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro/No binario')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='sisben',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='tipo_zona',
            field=models.CharField(blank=True, choices=[('URBANO', 'Urbano'), ('RURAL', 'Rural')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cedula',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='celular',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ciudad_residencia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
