# Generated by Django 5.0.7 on 2025-10-02 15:18

import apps.candidates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidato_barrio_candidato_caja_compensacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO(A)', 'Soltero(a)'), ('CASADO(A)', 'Casado(a)'), ('UNIÓN LIBRE', 'Unión libre'), ('SEPARADO(A)', 'Separado(a)'), ('DIVORCIADO(A)', 'Divorciado(a)'), ('VIUDO(A)', 'Viudo(a)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='lugar_expedicion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='puntaje_sisben',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CandidatoSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALUD', 'Historial salud/EPS'), ('PENSIONES', 'Historial pensiones'), ('CAJA', 'Historial caja de compensación'), ('FOTO_FRENTE', 'Foto frente')], max_length=20)),
                ('archivo', models.FileField(upload_to=apps.candidates.models.candidato_upload_path)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soportes', to='candidates.candidato')),
            ],
        ),
    ]
