# Generated by Django 5.0.7 on 2025-10-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidato_estado_civil_candidato_lugar_expedicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='telefono2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidatosoporte',
            name='tipo',
            field=models.CharField(choices=[('SALUD', 'Historial salud/EPS'), ('PENSIONES', 'Historial pensiones'), ('CAJA', 'Historial caja de compensación'), ('CESANTIAS', 'Historial cesantías'), ('FOTO_FRENTE', 'Foto frente')], max_length=20),
        ),
    ]
