# Generated by Django 5.0.7 on 2025-10-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidato_telefono2_alter_candidatosoporte_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='telefono2',
        ),
        migrations.AlterField(
            model_name='candidatosoporte',
            name='tipo',
            field=models.CharField(choices=[('SALUD', 'Historial salud/EPS'), ('PENSIONES', 'Historial pensiones'), ('CAJA', 'Historial caja de compensación'), ('FOTO_FRENTE', 'Foto frente')], max_length=20),
        ),
    ]
