# Generated by Django 5.0.7 on 2025-10-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_remove_candidato_telefono2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatosoporte',
            name='tipo',
            field=models.CharField(choices=[('SALUD', 'Historial salud/EPS'), ('PENSIONES', 'Historial pensiones'), ('CAJA', 'Historial caja de compensación'), ('CESANTIAS', 'Soporte cesantías'), ('FOTO_FRENTE', 'Foto frente')], max_length=20),
        ),
    ]
