# Generated by Django 5.2.4 on 2025-10-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_candidatosoporte_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='libreta_militar_clase',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='libreta_militar_distrito',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='libreta_militar_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='licencia_transito_categoria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='licencia_transito_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='licencia_transito_vence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatosoporte',
            name='tipo',
            field=models.CharField(choices=[('CEDULA', 'Copia cédula'), ('LIBRETA_MILITAR', 'Libreta militar'), ('LICENCIA_TRANSITO', 'Licencia de tránsito'), ('SALUD', 'Historial salud/EPS'), ('PENSIONES', 'Historial pensiones'), ('CAJA', 'Historial caja de compensación'), ('CESANTIAS', 'Soporte cesantías'), ('FOTO_FRENTE', 'Foto frente')], max_length=20),
        ),
    ]
