# Generated by Django 5.0.7 on 2026-02-17 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidato_libreta_militar_clase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=30)),
                ('nombre_pareja', models.CharField(blank=True, max_length=150, null=True)),
                ('ocupacion_pareja', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa_pareja', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_familiar', to='candidates.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=150)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('vive_con_el', models.BooleanField(default=False)),
                ('informacion_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='candidates.informacionfamiliar')),
            ],
        ),
        migrations.CreateModel(
            name='Conviviente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=30)),
                ('nombre_apellido', models.CharField(max_length=150)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('informacion_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convivientes', to='candidates.informacionfamiliar')),
            ],
        ),
        migrations.CreateModel(
            name='Pariente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=30)),
                ('nombre_apellido', models.CharField(max_length=150)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('vive_con_el', models.BooleanField(default=False)),
                ('informacion_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parientes', to='candidates.informacionfamiliar')),
            ],
        ),
    ]
