# Generated by Django 5.0.7 on 2026-02-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_informacionfamiliar_hijo_conviviente_pariente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_vivienda', models.CharField(max_length=30)),
                ('iluminacion', models.CharField(max_length=20)),
                ('ventilacion', models.CharField(max_length=20)),
                ('aseo', models.CharField(max_length=20)),
                ('servicios_publicos', models.CharField(max_length=200)),
                ('condiciones', models.CharField(max_length=30)),
                ('tenencia', models.CharField(max_length=20)),
                ('tipo_inmueble', models.CharField(max_length=20)),
                ('espacios', models.CharField(max_length=200)),
                ('vias_aproximacion', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_vivienda', to='candidates.candidato')),
            ],
        ),
    ]
