# Generated by Django 5.0.7 on 2026-02-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_descripcionvivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='discapacidad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='estado_migratorio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='idiomas',
            field=models.CharField(blank=True, help_text='Idiomas separados por coma', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
