# Generated by Django 5.0.7 on 2025-09-03 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizacion_firmada', models.BooleanField(default=False)),
                ('autorizacion_fecha', models.DateTimeField(blank=True, null=True)),
                ('progreso', models.FloatField(default=0.0)),
                ('score_cuantitativo', models.FloatField(default=0.0)),
                ('nivel_cualitativo', models.CharField(default='BAJO', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstudioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LISTAS_RESTRICTIVAS', 'Listas Restrictivas'), ('TITULOS_ACADEMICOS', 'Titulos Academicos'), ('CERT_LABORALES', 'Cert Laborales'), ('VISITA_DOMICILIARIA', 'Visita Domiciliaria')], max_length=40)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('puntaje', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='studies.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='CREADA', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='estudio',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudio', to='studies.solicitud'),
        ),
    ]
