# Generated by Django 5.0.7 on 2025-09-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudioitem',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
