# Generated by Django 5.0.7 on 2025-09-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_estudioitem_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioConsentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GENERAL', 'Autorización de tratamiento de datos'), ('CENTRALES', 'Consulta en centrales de riesgo'), ('ACADEMICO', 'Verificación académica')], max_length=20)),
                ('aceptado', models.BooleanField(default=False)),
                ('firmado_at', models.DateTimeField(blank=True, null=True)),
                ('firma', models.FileField(blank=True, null=True, upload_to='firmas/')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='studies.estudio')),
            ],
            options={
                'unique_together': {('estudio', 'tipo')},
            },
        ),
    ]
