# Generated by Django 5.0.7 on 2025-09-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidato_barrio_candidato_caja_compensacion_and_more'),
        ('studies', '0003_estudioconsentimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=255)),
                ('fecha_graduacion', models.DateField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('presenta_original', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='academicos/')),
                ('archivo_tipo', models.CharField(choices=[('DIPLOMA', 'Diploma'), ('ACTA', 'Acta de grado'), ('OTRO', 'Otro')], default='DIPLOMA', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicos', to='candidates.candidato')),
                ('estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academicos', to='studies.estudio')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ingreso', models.DateField(blank=True, null=True)),
                ('retiro', models.DateField(blank=True, null=True)),
                ('motivo_retiro', models.CharField(blank=True, max_length=255)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('FIJO', 'Fijo'), ('INDEFINIDO', 'Indefinido'), ('OBRA', 'Obra/Labor'), ('OTRO', 'Otro')], max_length=12)),
                ('jefe_inmediato', models.CharField(blank=True, max_length=255)),
                ('verificada_camara', models.BooleanField(default=False)),
                ('volveria_contratar', models.BooleanField(blank=True, null=True)),
                ('concepto', models.TextField(blank=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='laborales/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laborales', to='candidates.candidato')),
                ('estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laborales', to='studies.estudio')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
