# Generated by Django 5.0.7 on 2025-09-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_academico_laboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='acta_numero',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='academico',
            name='concepto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='academico',
            name='folio_numero',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='academico',
            name='grado',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='academico',
            name='libro_registro',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='academico',
            name='rector',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='academico',
            name='secretario',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
