# Generated by Django 5.0.7 on 2025-09-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_academico_acta_numero_academico_concepto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='decision_final',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APTO', 'Apto'), ('NO_APTO', 'No apto')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='estudio',
            name='enviado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='estado',
            field=models.CharField(choices=[('EN_CAPTURA', 'En captura'), ('EN_REVISION', 'En revisión'), ('DEVUELTO', 'Devuelto al candidato'), ('CERRADO', 'Cerrado')], db_index=True, default='EN_CAPTURA', max_length=20),
        ),
        migrations.AddField(
            model_name='estudio',
            name='finalizado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='observacion_analista',
            field=models.TextField(blank=True, default=''),
        ),
    ]
