# Generated by Django 5.0.7 on 2025-09-09 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_estudio_decision_final_estudio_enviado_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('DOC', 'Documento general'), ('CENTRALES', 'Centrales de riesgo')], default='DOC', max_length=20)),
                ('archivo', models.FileField(upload_to='estudios/%Y/%m/')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('subido_por', models.CharField(choices=[('CANDIDATO', 'CANDIDATO'), ('ANALISTA', 'ANALISTA')], default='CANDIDATO', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='studies.estudio')),
            ],
        ),
    ]
