# Generated by Django 5.0.7 on 2025-09-10 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidato_barrio_candidato_caja_compensacion_and_more'),
        ('studies', '0007_estudiodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudioitem',
            name='tipo',
            field=models.CharField(choices=[('LISTAS_RESTRICTIVAS', 'Listas Restrictivas'), ('TITULOS_ACADEMICOS', 'Titulos Academicos'), ('CERT_LABORALES', 'Cert Laborales'), ('VISITA_DOMICILIARIA', 'Visita Domiciliaria'), ('INFO_ECONOMICA', 'Info Economica')], max_length=40),
        ),
        migrations.CreateModel(
            name='InfoEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registra_negativos', models.BooleanField(blank=True, null=True)),
                ('central', models.CharField(blank=True, default='', max_length=80)),
                ('deuda_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('entidad_reporta', models.CharField(blank=True, default='', max_length=255)),
                ('acuerdo_pago', models.BooleanField(blank=True, null=True)),
                ('fecha_acuerdo', models.DateField(blank=True, null=True)),
                ('valor_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('es_codeudor', models.BooleanField(blank=True, null=True)),
                ('productos', models.JSONField(blank=True, default=dict)),
                ('ingresos', models.JSONField(blank=True, default=dict)),
                ('egresos', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_economica', to='candidates.candidato')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_economica', to='studies.estudio')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
