# Generated by Django 5.0.7 on 2025-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_alter_estudioitem_tipo_infoeconomica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudioitem',
            name='tipo',
            field=models.CharField(choices=[('LISTAS_RESTRICTIVAS', 'Listas Restrictivas'), ('TITULOS_ACADEMICOS', 'Titulos Academicos'), ('CERT_LABORALES', 'Cert Laborales'), ('VISITA_DOMICILIARIA', 'Visita Domiciliaria')], max_length=40),
        ),
        migrations.DeleteModel(
            name='InfoEconomica',
        ),
    ]
