# Generated by Django 5.0.7 on 2025-09-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidato_barrio_candidato_caja_compensacion_and_more'),
        ('studies', '0009_alter_estudioitem_tipo_delete_infoeconomica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('central', models.CharField(blank=True, max_length=120)),
                ('registra_negativos', models.BooleanField(blank=True, null=True)),
                ('deuda_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='economica/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economicas', to='candidates.candidato')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economicas', to='studies.estudio')),
            ],
        ),
    ]
