# Generated by Django 5.0.7 on 2025-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_economica'),
    ]

    operations = [
        migrations.AddField(
            model_name='economica',
            name='acuerdo_pago',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economica',
            name='cruce',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='economica',
            name='egresos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='economica',
            name='es_codeudor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economica',
            name='fecha_acuerdo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economica',
            name='ingresos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='economica',
            name='total_egresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='economica',
            name='total_ingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='economica',
            name='valor_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
