# Generated by Django 5.0.7 on 2025-09-21 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidato_barrio_candidato_caja_compensacion_and_more'),
        ('studies', '0011_economica_acuerdo_pago_economica_cruce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FACHADA_GENERAL', 'Fachada general'), ('FACHADA_POSTERIOR', 'Fotografía posterior fachada'), ('NOMENCLATURA', 'Vista nomenclatura'), ('ENTRADA', 'Entrada vivienda'), ('FRENTE_ASPIRANTE', 'Fotografía reciente frente aspirante'), ('SALA_GENERAL', 'Vista general sala'), ('COMEDOR', 'Comedor'), ('COCINA', 'Cocina'), ('BANO_1', 'Baño 1'), ('BANO_2', 'Baño 2'), ('ZONA_LAVADO', 'Zona de lavado'), ('ESTUDIO', 'Estudio'), ('PATIO_BALCON_1', 'Patio o balcón 1'), ('PATIO_BALCON_2', 'Patio o balcón 2'), ('SALA_POSTERIOR', 'Vista posterior sala'), ('HABITACION_1', 'Habitación 1'), ('HABITACION_2', 'Habitación 2'), ('HABITACION_3', 'Habitación 3'), ('ZONAS_ALED_1', 'Vista posterior zonas aledañas 1'), ('ZONAS_ALED_2', 'Vista posterior zonas aledañas 2')], db_index=True, max_length=40)),
                ('no_aplica', models.BooleanField(default=False)),
                ('archivo', models.ImageField(blank=True, null=True, upload_to='anexos/%Y/%m/')),
                ('comentario', models.CharField(blank=True, default='', max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_foto', to='candidates.candidato')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_foto', to='studies.estudio')),
            ],
            options={
                'ordering': ['orden', 'tipo', '-creado'],
                'unique_together': {('estudio', 'tipo')},
            },
        ),
    ]
