# Generated by Django 5.0.7 on 2025-09-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_anexofoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudioitem',
            name='tipo',
            field=models.CharField(choices=[('LISTAS_RESTRICTIVAS', 'Listas Restrictivas'), ('TITULOS_ACADEMICOS', 'Titulos Academicos'), ('CERT_LABORALES', 'Cert Laborales'), ('VISITA_DOMICILIARIA', 'Visita Domiciliaria'), ('ANEXOS_FOTOGRAFICOS', 'Anexos Fotograficos')], max_length=40),
        ),
    ]
