# Generated by Django 5.0.7 on 2025-09-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_alter_estudioitem_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudioconsentimiento',
            name='firma_imagen',
            field=models.FileField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
