# Generated by Django 5.0.7 on 2025-10-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0015_evaluaciontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='jefe_registro',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='academico',
            name='secretario_academico',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='academico',
            name='secretario_general',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
