# Generated by Django 5.0.7 on 2025-10-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0016_academico_jefe_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='categoria',
            field=models.CharField(choices=[('FORMAL', 'Formal'), ('NO_FORMAL', 'No formal')], default='FORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='academico',
            name='colegio_regulador',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='academico',
            name='matricula_numero',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='academico',
            name='tiene_matricula',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
