# Generated by Django 5.0.7 on 2025-10-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0017_academico_categoria_academico_colegio_regulador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='economica',
            name='productos_financieros',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
