# Generated by Django 5.0.7 on 2025-10-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_economica_productos_financieros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexofoto',
            name='tipo',
            field=models.CharField(choices=[('FACHADA_GENERAL', 'Fachada general'), ('FACHADA_POSTERIOR', 'Fotografía posterior fachada'), ('NOMENCLATURA', 'Vista nomenclatura'), ('ENTRADA', 'Entrada vivienda'), ('FRENTE_ASPIRANTE', 'Fotografía reciente frente aspirante'), ('SALA_GENERAL', 'Vista general sala'), ('COMEDOR', 'Comedor'), ('COCINA', 'Cocina'), ('BANO_1', 'Baño 1'), ('BANO_2', 'Baño 2'), ('ZONA_LAVADO', 'Zona de lavado'), ('ESTUDIO', 'Estudio'), ('HALL_CORREDOR', 'Hall o corredor'), ('ESCALERAS', 'Escaleras'), ('PATIO_BALCON_1', 'Patio o balcón 1'), ('PATIO_BALCON_2', 'Patio o balcón 2'), ('SALA_POSTERIOR', 'Vista posterior sala'), ('HABITACION_1', 'Habitación 1'), ('HABITACION_2', 'Habitación 2'), ('HABITACION_3', 'Habitación 3'), ('ZONAS_ALED_1', 'Vista posterior zonas aledañas 1'), ('ZONAS_ALED_2', 'Vista posterior zonas aledañas 2')], db_index=True, max_length=40),
        ),
    ]
