# Generated by Django 5.0.7 on 2025-10-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0019_alter_anexofoto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboral',
            name='referencia_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='laboral',
            name='referencia_telefono',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anexofoto',
            name='tipo',
            field=models.CharField(choices=[('FACHADA_GENERAL', 'Fachada general'), ('FACHADA_POSTERIOR', 'Fotografía posterior fachada'), ('NOMENCLATURA', 'Vista nomenclatura'), ('ENTRADA', 'Entrada vivienda'), ('FRENTE_ASPIRANTE', 'Fotografía reciente frente aspirante'), ('SALA_GENERAL', 'Vista general sala'), ('SALA_POSTERIOR', 'Vista posterior sala'), ('COMEDOR', 'Comedor'), ('COCINA', 'Cocina'), ('BANO_1', 'Baño 1'), ('BANO_2', 'Baño 2'), ('ZONA_LAVADO', 'Zona de lavado'), ('ESTUDIO', 'Estudio'), ('HALL_CORREDOR', 'Hall o corredor'), ('ESCALERAS', 'Escaleras'), ('PATIO_1', 'Patio 1'), ('PATIO_2', 'Patio 2'), ('BALCON_1', 'Balcón 1'), ('BALCON_2', 'Balcón 2'), ('HABITACION_1', 'Habitación 1'), ('HABITACION_2', 'Habitación 2'), ('HABITACION_3', 'Habitación 3'), ('ZONAS_ALED_1', 'Vista posterior zonas aledañas 1'), ('ZONAS_ALED_2', 'Vista posterior zonas aledañas 2'), ('ZONAS_COMUNES', 'Zonas comunes'), ('ZONAS_HUMEDAS', 'Zonas húmedas'), ('PARQUES', 'Parques'), ('GIMNASIO', 'Gimnasio'), ('TERRAZA', 'Terraza'), ('PARQUEADERO_1', 'Parqueadero 1'), ('PARQUEADERO_2', 'Parqueadero 2'), ('PATIO_BALCON_1', 'Patio o balcón 1'), ('PATIO_BALCON_2', 'Patio o balcón 2')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='laboral',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('FIJO', 'Fijo'), ('INDEFINIDO', 'Indefinido'), ('OBRA', 'Obra/Labor'), ('PRESTACION', 'Prestación de servicios'), ('APRENDIZAJE', 'Aprendizaje'), ('OTRO', 'Otro')], max_length=12),
        ),
    ]
