# Generated by Django 5.0.7 on 2025-10-03 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0020_laboral_referencia_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(max_length=30)),
                ('relacion', models.CharField(blank=True, max_length=120)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='studies.estudio')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
