# Generated by Django 5.2.4 on 2025-10-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0021_estudioreferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='cert_antecedentes',
            field=models.FileField(blank=True, null=True, upload_to='academicos/'),
        ),
        migrations.AddField(
            model_name='academico',
            name='matricula_archivo',
            field=models.FileField(blank=True, null=True, upload_to='academicos/'),
        ),
        migrations.AddField(
            model_name='academico',
            name='nivel',
            field=models.CharField(blank=True, choices=[('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('BACHILLER', 'Bachiller'), ('TECNICO', 'Técnico'), ('TECNOLOGO', 'Tecnólogo'), ('PROFESIONAL', 'Profesional'), ('ESPECIALIZACION', 'Especialización'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20, null=True),
        ),
    ]
