# Generated by Django 5.0.7 on 2025-10-14 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidato_libreta_militar_clase_and_more'),
        ('studies', '0022_academico_cert_antecedentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexofoto',
            name='tipo',
            field=models.CharField(choices=[('FACHADA_GENERAL', 'Fachada general'), ('FACHADA_POSTERIOR', 'Fotografía posterior fachada'), ('NOMENCLATURA', 'Vista nomenclatura (zoom)'), ('ENTRADA', 'Entrada vivienda'), ('FRENTE_ASPIRANTE', 'Fotografía reciente frente aspirante'), ('SALA_GENERAL', 'Vista general sala'), ('SALA_POSTERIOR', 'Vista posterior sala'), ('COMEDOR', 'Comedor'), ('COCINA', 'Cocina'), ('BANO_1', 'Baño 1'), ('BANO_2', 'Baño 2'), ('ZONA_LAVADO', 'Zona de lavado'), ('ESTUDIO', 'Estudio'), ('HALL_CORREDOR', 'Hall o corredor'), ('ESCALERAS', 'Escaleras'), ('PATIO_1', 'Patio 1'), ('PATIO_2', 'Patio 2'), ('BALCON_1', 'Balcón 1'), ('BALCON_2', 'Balcón 2'), ('HABITACION_1', 'Habitación 1'), ('HABITACION_2', 'Habitación 2'), ('HABITACION_3', 'Habitación 3'), ('ZONAS_ALED_1', 'Vista posterior zonas aledañas 1'), ('ZONAS_ALED_2', 'Vista posterior zonas aledañas 2'), ('ZONAS_COMUNES', 'Zonas comunes'), ('ZONAS_HUMEDAS', 'Zonas húmedas'), ('PARQUES', 'Parques'), ('GIMNASIO', 'Gimnasio'), ('TERRAZA', 'Terraza'), ('PARQUEADERO_1', 'Parqueadero 1'), ('PARQUEADERO_2', 'Parqueadero 2'), ('TORRE', 'Torre'), ('RECEPCION', 'Recepción'), ('ASCENSORES', 'Ascensores'), ('TURCO', 'Turco'), ('SAUNA', 'Sauna'), ('JACUZZI', 'Jacuzzi'), ('BBQ', 'BBQ'), ('OTRAS_1', 'Otras fotografías 1'), ('OTRAS_2', 'Otras fotografías 2'), ('OTRAS_3', 'Otras fotografías 3'), ('OTRAS_4', 'Otras fotografías 4'), ('PATIO_BALCON_1', 'Patio o balcón 1'), ('PATIO_BALCON_2', 'Patio o balcón 2')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='estudioitem',
            name='tipo',
            field=models.CharField(choices=[('LISTAS_RESTRICTIVAS', 'Listas Restrictivas'), ('TITULOS_ACADEMICOS', 'Titulos Academicos'), ('CERT_LABORALES', 'Cert Laborales'), ('VISITA_DOMICILIARIA', 'Visita Domiciliaria'), ('ANEXOS_FOTOGRAFICOS', 'Anexos Fotograficos'), ('REFERENCIAS_PERSONALES', 'Referencias Personales'), ('INFO_PATRIMONIO', 'Info Patrimonio')], max_length=40),
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmuebles_propios', models.BooleanField(blank=True, null=True)),
                ('inmuebles_heredados', models.BooleanField(blank=True, null=True)),
                ('obs_ubicacion', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_casa', models.BooleanField(blank=True, null=True)),
                ('tipo_apartamento', models.BooleanField(blank=True, null=True)),
                ('tipo_finca', models.BooleanField(blank=True, null=True)),
                ('tipo_casa_lote', models.BooleanField(blank=True, null=True)),
                ('tipo_lote', models.BooleanField(blank=True, null=True)),
                ('tipo_edificio', models.BooleanField(blank=True, null=True)),
                ('tipo_otro_consultorio', models.BooleanField(blank=True, null=True)),
                ('tipo_otro_text', models.CharField(blank=True, default='', max_length=120)),
                ('bm_vehiculo', models.BooleanField(blank=True, null=True)),
                ('bm_motocicleta', models.BooleanField(blank=True, null=True)),
                ('bm_bicicleta', models.BooleanField(blank=True, null=True)),
                ('bm_fideicomiso', models.BooleanField(blank=True, null=True)),
                ('bm_joyas_arte', models.BooleanField(blank=True, null=True)),
                ('bm_pc_portatil', models.BooleanField(blank=True, null=True)),
                ('bm_celular_tablet', models.BooleanField(blank=True, null=True)),
                ('obs_muebles', models.CharField(blank=True, default='', max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonios', to='candidates.candidato')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonios', to='studies.estudio')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('ocupacion', models.CharField(blank=True, max_length=255)),
                ('empresa', models.CharField(blank=True, max_length=255)),
                ('tiempo_conocerse', models.CharField(blank=True, max_length=120)),
                ('concepto_sobre_referenciado', models.TextField(blank=True)),
                ('concepto_analista', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refs_personales', to='candidates.candidato')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refs_personales', to='studies.estudio')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
