# Generated by Django 5.0.7 on 2026-02-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('studies', '0023_alter_anexofoto_tipo_alter_estudioitem_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteConfiguracionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_tipo', models.CharField(choices=[('LISTAS_RESTRICTIVAS', 'Listas Restrictivas'), ('TITULOS_ACADEMICOS', 'Titulos Academicos'), ('CERT_LABORALES', 'Cert Laborales'), ('VISITA_DOMICILIARIA', 'Visita Domiciliaria'), ('ANEXOS_FOTOGRAFICOS', 'Anexos Fotograficos'), ('REFERENCIAS_PERSONALES', 'Referencias Personales'), ('INFO_PATRIMONIO', 'Info Patrimonio')], max_length=40)),
                ('no_determinante', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de ítem no determinante',
                'verbose_name_plural': 'Configuraciones de ítems no determinantes',
                'unique_together': {('empresa', 'item_tipo')},
            },
        ),
    ]
