# Generated by Django 5.0.7 on 2026-02-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0024_clienteconfiguracionitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClienteConfiguracionItems',
        ),
    ]
