# Generated by Django 5.0.7 on 2026-02-28 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('studies', '0025_delete_clienteconfiguracionitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteConfiguracionFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('subitem', models.CharField(max_length=100)),
                ('excluido', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_formulario', to='accounts.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'item', 'subitem')},
            },
        ),
    ]
