# Generated by Django 5.0.7 on 2026-03-02 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('studies', '0026_clienteconfiguracionformulario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePoliticaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=50)),
                ('opcion', models.CharField(max_length=50)),
                ('no_relevante', models.BooleanField(default=True)),
                ('bloqueado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politica_configuracion', to='accounts.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politica_configuracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('empresa', 'criterio', 'opcion')},
            },
        ),
    ]
