# Generated by Django 4.2.16 on 2026-03-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0027_clientepoliticaconfiguracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='a_consideracion_cliente',
            field=models.BooleanField(default=False, help_text='Indica si el estudio fue creado bajo configuración personalizada del cliente (criterios no relevantes)'),
        ),
    ]
