# Generated by Django 4.2.16 on 2026-04-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0032_estudioconsentimiento_firma_draw'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotDisponibilidadAnalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_disponibilidad', to='studies.estudio')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='disponibilidadreunioncandidato',
            name='slot_seleccionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seleccionado_por', to='studies.slotdisponibilidadanalista'),
        ),
    ]
