# Generated by Django 5.0.7 on 2025-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='enviado_revision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('OBSERVACION', 'Con observaciones'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='visible_para_analista',
            field=models.BooleanField(default=False),
        ),
    ]
