# Generated by Django 5.0.7 on 2025-09-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documento_enviado_revision_at_documento_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='enviado_revision_at',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='visible_para_analista',
        ),
    ]
