# Generated by Django 5.0.7 on 2025-09-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaDomiciliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inmueble', models.CharField(blank=True, max_length=30)),
                ('habitaciones', models.IntegerField(default=0)),
                ('banos', models.IntegerField(default=0)),
                ('via_aproximacion', models.CharField(blank=True, max_length=120)),
                ('nomenclatura', models.CharField(blank=True, max_length=120)),
                ('riesgo', models.IntegerField(default=0)),
                ('comentario', models.TextField(blank=True)),
                ('estudio_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visita', to='studies.estudioitem')),
            ],
        ),
        migrations.CreateModel(
            name='FotoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='visitas/')),
                ('etiqueta', models.CharField(blank=True, max_length=60)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='visits.visitadomiciliaria')),
            ],
        ),
    ]
